[package]
name = "todo-app"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["./migration/"]

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
sqlx = { version = "0.8.6", features = [
  "mysql",
  "macros",
  "runtime-tokio-rustls",
] }
dotenv = "0.15.0"
