services:
  directus:
    image: directus/directus:latest
    ports: 
      - "8055:8055"
    environment:
      KEY: "key"
      SECRET: "secret"
      ADMIN_EMAIL: "jo@spw.com"
      ADMIN_PASSWORD: "password"
      DB_CLIENT: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_DATABASE: "todo"
      DB_USER: "root"
      DB_PASSWORD: "password"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.1.0
    container_name: todos
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3304:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
